# Generated by Django 4.2.4 on 2023-09-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0020_rename_name_producttype_nametype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesize', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
