# Generated by Django 4.2.4 on 2023-10-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0021_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
