# Generated by Django 4.2.4 on 2023-10-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0024_alter_sellerprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
