# Generated by Django 4.2.4 on 2023-10-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0028_payment_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
