# Generated by Django 4.2.4 on 2023-10-25 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0032_order_payment_id_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_charge',
            field=models.FloatField(default=40.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(),
        ),
    ]
