# Generated by Django 4.2.4 on 2024-01-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0037_auctionitem_delete_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
