# Generated by Django 4.2.4 on 2024-01-22 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0040_alter_user_bid_bid_price_alter_user_bid_ending_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_bid',
            name='bid_price',
        ),
        migrations.RemoveField(
            model_name='user_bid',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='user_bid',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user_bid',
            name='starting_price',
        ),
        migrations.AddField(
            model_name='user_bid',
            name='art_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='artvendermini.auctionitem'),
            preserve_default=False,
        ),
    ]
