# Generated by Django 4.2.4 on 2024-01-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0041_remove_user_bid_bid_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_bid',
            old_name='art_id',
            new_name='art',
        ),
    ]
