# Generated by Django 4.2.4 on 2024-01-22 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0043_user_bid_bid_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_bid',
            name='art',
        ),
        migrations.AddField(
            model_name='user_bid',
            name='auction_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='artvendermini.auctionitem'),
            preserve_default=False,
        ),
    ]
