# Generated by Django 4.2.4 on 2024-02-06 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artvendermini', '0046_auctionlisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer_address', models.TextField()),
                ('buyer_pincode', models.CharField(max_length=10)),
                ('auction_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artvendermini.auctionlisting')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
