# Generated by Django 4.2.4 on 2024-02-12 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0047_auctionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bid',
            name='current_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
