# Generated by Django 4.2.4 on 2024-02-19 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artvendermini', '0048_user_bid_current_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionRejectAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artvendermini.auctionitem')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
