# Generated by Django 4.2.4 on 2024-02-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0049_auctionrejectadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
