# Generated by Django 4.2.4 on 2024-02-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0050_auctionitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='latest_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
