# Generated by Django 4.2.4 on 2024-02-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0051_alter_auctionlisting_latest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='latest_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
