# Generated by Django 4.2.4 on 2024-02-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0053_deliveryprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprofile',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='max_delivery_km',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='pin',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
