# Generated by Django 4.2.4 on 2024-02-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0057_deliveryprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='phone',
        ),
    ]
