# Generated by Django 4.2.4 on 2024-02-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0058_remove_deliveryprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprofile',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='max_delivery_km',
            field=models.IntegerField(null=True),
        ),
    ]
