# Generated by Django 4.2.4 on 2024-02-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0060_alter_deliveryprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprofile',
            name='pin',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
