# Generated by Django 4.2.4 on 2024-02-27 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0068_alter_deliveryprofile_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='userdata',
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='userdata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artvendermini.userdata'),
        ),
    ]
