# Generated by Django 4.2.4 on 2024-02-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0071_remove_deliveryprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryregistration',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
