# Generated by Django 4.2.4 on 2024-02-28 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artvendermini', '0072_remove_deliveryregistration_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionorder',
            name='auction_listing',
        ),
        migrations.RemoveField(
            model_name='auctionorder',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='auctionorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='auctionorder',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='buyer_city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='buyer_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='buyer_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='buyer_locality',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='buyer_phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='buyer_state',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
