# Generated by Django 4.2.4 on 2024-02-28 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0074_auctionorder_auction_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionorder',
            name='auction_item',
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='auctionlisting',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='artvendermini.auctionlisting'),
            preserve_default=False,
        ),
    ]
