# Generated by Django 4.2.4 on 2024-02-28 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0075_remove_auctionorder_auction_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionorder',
            name='auctionlisting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artvendermini.auctionlisting'),
        ),
    ]
