# Generated by Django 4.2.4 on 2024-02-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0076_alter_auctionorder_auctionlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionorder',
            name='auctionlisting',
        ),
    ]
