# Generated by Django 4.2.4 on 2024-02-28 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0077_remove_auctionorder_auctionlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionorder',
            name='auctionlisting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artvendermini.auctionlisting'),
        ),
    ]
