# Generated by Django 4.2.4 on 2024-03-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0078_auctionorder_auctionlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionorder',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
