# Generated by Django 4.2.4 on 2024-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0079_auctionorder_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryregistration',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='deliveryregistration',
            name='district',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryregistration',
            name='latitude',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryregistration',
            name='longitude',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryregistration',
            name='max_delivery_km',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveryregistration',
            name='pin',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryregistration',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
