# Generated by Django 4.2.4 on 2024-03-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0080_deliveryregistration_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='max_delivery_km',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='state',
        ),
    ]
