# Generated by Django 4.2.4 on 2024-03-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0086_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
