# Generated by Django 4.2.4 on 2024-03-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0087_productdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='otp_value',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
