# Generated by Django 4.2.4 on 2024-03-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0088_productdetails_otp_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='otp_value',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
