# Generated by Django 4.2.4 on 2024-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0090_alter_productdetails_otp_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='otp_value',
            field=models.CharField(choices=[('failed', 'Failed'), ('sucess', 'Sucess')], default='sucess', max_length=10),
        ),
    ]
