# Generated by Django 4.2.4 on 2024-03-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0097_productdetails_otp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
    ]
