# Generated by Django 4.2.4 on 2024-03-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0098_alter_productdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
