# Generated by Django 4.2.4 on 2024-03-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0099_productdetails_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='date',
        ),
    ]
