# Generated by Django 4.2.4 on 2024-03-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0103_productdetails_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='date',
        ),
    ]
