# Generated by Django 4.2.4 on 2024-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0104_remove_productdetails_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
