# Generated by Django 4.2.4 on 2024-03-18 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0107_rename_buyer_rating_customer_rating_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average_rating',
        ),
    ]
