# Generated by Django 4.2.4 on 2024-03-19 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0108_remove_rating_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='certificate',
            field=models.FileField(blank=True, upload_to='admin_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
