# Generated by Django 4.2.4 on 2024-03-19 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0109_userdata_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='certificate_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approved'), ('reject', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='admin_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
