# Generated by Django 4.2.4 on 2024-03-19 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0110_userdata_certificate_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='certificate_status',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='certificate',
            field=models.FileField(blank=True, default=1, upload_to='admin_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
            preserve_default=False,
        ),
    ]
