# Generated by Django 4.2.4 on 2024-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0111_remove_userdata_certificate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='certificate_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Approved', max_length=10),
        ),
    ]
