# Generated by Django 4.2.4 on 2024-03-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0112_userdata_certificate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='certificate_status',
        ),
    ]
