# Generated by Django 4.2.4 on 2024-03-20 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0114_userdata_certificate_userdata_certificate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='certificate',
            field=models.FileField(null=True, upload_to='admin_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
