# Generated by Django 4.2.4 on 2024-03-20 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0115_alter_userdata_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='certificate',
            field=models.FileField(blank=True, default=1, upload_to='admin_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
            preserve_default=False,
        ),
    ]
