# Generated by Django 4.2.4 on 2024-03-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0117_remove_uploadartdetail_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadartdetail',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
    ]
