# Generated by Django 4.2.4 on 2024-04-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0118_uploadartdetail_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='Pending', max_length=10),
        ),
    ]
