# Generated by Django 4.2.4 on 2024-04-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0120_auctionlisting_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_bid',
        ),
    ]
