# Generated by Django 4.2.4 on 2024-04-04 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0121_remove_auctionlisting_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionorder',
            name='auction_item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='artvendermini.auctionitem'),
            preserve_default=False,
        ),
    ]
