# Generated by Django 4.2.4 on 2024-04-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artvendermini', '0122_auctionorder_auction_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionorder',
            name='auction_item',
        ),
    ]
